org.gradle.jvmargs=-Xmx2500m -Dfile.encoding=UTF-8 -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=18080 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=18080 -Dhttp.nonProxyHosts=localhost|127.0.0.1
org.gradle.caching=true
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.paths=/root/.local/share/mise/installs/java
org.gradle.java.home=/root/.local/share/mise/installs/java/17.0.2
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=18080
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=18080
systemProp.http.nonProxyHosts=localhost|127.0.0.1
android.suppressUnsupportedCompileSdk=36
