org.gradle.jvmargs=-Xmx2500m -Dfile.encoding=UTF-8 --add-exports jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=18080 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=18080 -Dhttp.nonProxyHosts=localhost|127.0.0.1
org.gradle.caching=true
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.paths=/opt/java21
org.gradle.java.home=/opt/java21
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=18080
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=18080
systemProp.http.nonProxyHosts=localhost|127.0.0.1
android.suppressUnsupportedCompileSdk=36
