pluginManagement {
    repositories {
        maven { url = "https://maven.aliyun.com/repository/google" }
        maven { url = "https://maven.aliyun.com/repository/central" }
        maven { url = "https://maven.aliyun.com/repository/public" }
        google()
        mavenCentral()
        maven { url = "https://dl.google.com/dl/android/maven2" }
        maven { url = "https://maven.google.com" }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url = "https://maven.aliyun.com/repository/google" }
        maven { url = "https://maven.aliyun.com/repository/central" }
        maven { url = "https://maven.aliyun.com/repository/public" }
        maven { url = "https://jitpack.io" }
        mavenCentral()
        google()
        flatDir { dirs "$rootDir/app/libs" }
    }
}

include ':app'
include ':catvod'
include ':chaquo'
include ':quickjs'
rootProject.name = "MXboxS"
