package com.ssmhdssmhd.android.tv.event;

import org.greenrobot.eventbus.meta.SubscriberInfoIndex;

/** Auto-generated by EventBus annotation processor */
public class EventIndex implements SubscriberInfoIndex {
    @Override
    public org.greenrobot.eventbus.meta.SubscriberInfo getSubscriberInfo(Class<?> subscriberClass) {
        return null;
    }
}
